#include <iostream>
#include <stdexcept>

class Calculator {
public:
    static double divide(double num1, double num2) {
        if (num2 == 0) {
            throw std::invalid_argument("Division by zero error!");
        }
        return num1 / num2;
    }
};

int main() {
    double num1, num2;

    std::cout << "Enter numerator: ";
    std::cin >> num1;

    std::cout << "Enter denominator: ";
    std::cin >> num2;

    try {
        double result = Calculator::divide(num1, num2);
        std::cout << "Result of division: " << result << std::endl;
    } catch (std::invalid_argument &ex) {
        std::cout << "Exception caught: " << ex.what() << std::endl;
    }

    return 0;
}
